DOSALAMOS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/',include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import *
from django.urls.conf import include
from django.contrib import admin




urlpatterns = [
    path('',index,name='index'),
    path('reserva/',reserva, name='reserva'),
    path('registro/', registro, name="registro"),
    path('pago/', pago, name='pago'),
    path('listado-reserva/', listado_reserva, name='listado_reserva'),
    path('eliminar-reserva/<id>/',eliminar_reserva, name='eliminar_reserva'),
    path('modificar-reserva/str(<id>)/', modificar_reserva, name="modificar_reserva"),
    path('calendariomedico/',calendariomedico, name="calendariomedico"),
    path('listado-pago/',listado_pago, name= "listado_pago" ),
    path('fullcalendar/',fullcalendar, name= "fullcalendar" ),


]

core/models.py
from io import open_code
from django.db import models
from django.db.models.base import ModelState
from django.db.models.fields import DateTimeField, NullBooleanField
from django.contrib.auth.models import User
from datetime import date



# Create your models here.

class prevision(models.Model):
    nombre = models.CharField(max_length=30)
    def __str__(self):
        return self.nombre

class sexo(models.Model):
    nombre = models.CharField(max_length=15)
    def __str__(self):
        return self.nombre

class especialidad(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre
class fecha_Atencion(models.Model):
    fecha = models.DateField()
    def __str__(self):
        return str(self.fecha)

class medico(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE,null=False,default=None)
    nombre = models.CharField(max_length=50,default=None, null=True)
    especialidad = models.ForeignKey(especialidad,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.User)

class Reserva(models.Model):
    rut = models.CharField(max_length=9)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    prevision = models.ForeignKey(prevision,on_delete=models.CASCADE,default=None,null=True)
    fecha_Atencion = models.ForeignKey(fecha_Atencion,on_delete=models.CASCADE,default=None)
    sexo = models.ForeignKey(sexo, on_delete=models.CASCADE,default=None)
    correo = models.EmailField()
    especialidad = models.ForeignKey(especialidad, on_delete=models.CASCADE,default=None,null=True)
    medico = models.ForeignKey(medico, on_delete=models.CASCADE,default=None,null=True)
    def __str__(self):
        return str(self.id)


class Pago(models.Model):
    Reserva = models.ForeignKey(Reserva, on_delete = models.CASCADE, default=None)
    Total_pago = models.IntegerField()
    fecha_pago = models.DateTimeField(default=date.today)
    def __str__(self):
        return str(self.id)

class agenda(models.Model):
    medico = models.ForeignKey(medico,on_delete = models.CASCADE, default=None)
    fecha_asignado = models.DateField(default=date.today)
    reserva = models.ForeignKey(Reserva,on_delete = models.CASCADE, default=None)
    def __str__(self):
        return str(self.medico)

class fullcalendar(models.Model):
    fecha = models.DateTimeField(default=date.today)
    descripcion = models.CharField(max_length=50)

core/forms.py
from typing import ClassVar
from django import forms
from django.contrib import auth
from django.db import models
from django.db.models import fields
from django.forms import widgets    
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ReservaForm(forms.ModelForm):

    class Meta:
        model = Reserva
        fields = '__all__'


class CustomUserCreationForm(UserCreationForm):
    pass


class pagoForm(forms.ModelForm):

    class Meta:
        model = Pago
        fields = '__all__'

class fullcalendarForm(forms.ModelForm):

    class Meta:
        model = fullcalendar
        fields = '__all__'

core/views.py
from typing import get_args
from django.shortcuts import redirect, render, get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login
from django.contrib.messages.api import MessageFailure, success


# Create your views here.

def index(request):
    return render(request,'core/index.html')


def reserva(request):

    data = {
        'form': ReservaForm(),
    }

    if request.method == 'POST':
        formuluario = ReservaForm(data=request.POST)
        if formuluario.is_valid():
            formuluario.save()
            data["mensaje"] = "Reserva guardada correctamente"
        else:
            data["form"] = formuluario
            messages.success(request, "Reserva guardad correctamente")
            return render(request, 'core/reservahora.html', data)


def registro(request):
    data ={
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password =formulario.cleaned_data ["password1"])
            login(request, user)
            #redirigir al home
            return redirect(to=index)
    return render(request, 'registration/registro.html', data)


def pago(request):

    data = {
        'form': pagoForm(),
    }

    if request.method == 'POST':
        formularioo = pagoForm(data=request.POST)
        if formularioo.is_valid():
            formularioo.save()
            data["mensaje"] = "Pago exitoso"
        else:
            data["form"] = formularioo
    return render(request, 'core/registropago.html', data)

def listado_reserva(request):
    reserva = Reserva.objects.all()
    data = {
        'reserva': reserva
    }

    return render(request, 'core/listado_reserva.html', data)


def modificar_reserva(request, id):
    Reserv = get_object_or_404(Reserva, id=id)
    data={
        'form': ReservaForm(instance=Reserv)
    }
    if request.method == 'POST ':
        formulario = ReservaForm(data=request.POST, instance=Reserv)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="listado_reserva")
        else:
         data["form"] = formulario
    return render(request, 'core/modificar_reserva.html', data)



def calendariomedico(request):
    agendas = agenda.objects.all()
    data = {
        'agenda':agendas
    }
    return render(request, 'core/calendariomedico.html',data)



def listado_pago(request):
    pago = Pago.objects.all()

    data = {
        'pago': pago
    }
    return render(request, 'core/listado_pago.html', data)


def eliminar_reserva(request, id):
    reserva = get_object_or_404(Reserva, id =id)
    reserva.delete()
    return redirect(to="listado_reserva")

def fullcalendar(request):

    data = {
        'form': fullcalendarForm(),
    }

    if request.method == 'POST':
        formuluario = fullcalendarForm(data=request.POST)
        if formuluario.is_valid():
            formuluario.save()
            data["mensaje"] = "Reserva guardada correctamente"
        else:
            data["form"] = formuluario
    return render(request, 'core/fullcalendar.html', data)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dos Alamos</title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body>
    
    <header class="header" id="inicio">
            
        <nav class="navbar navbar-expand-lg navbar-light badge-light">
            <img src="/media/logo.png" width="250px" height="70px" alt="" href="#">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'index' %}">Inicio</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'reserva' %}">Reserva de horas</a>
                  </li>
                  {% if perms.core.view_reserva %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'listado_reserva' %}">Listado reserva</a>
                  </li>
                  {% endif %}
                  {% if perms.core.view_pago %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'listado_pago' %}">Listado pago</a>
                  </li>
                  {% endif %}
                  {% if perms.core.view_pago %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pago' %}">Registrar pago</a>
                  </li>
                  {% endif %}
                  
                  {% if perms.core.view_reserva %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'listado_reserva' %}">Listado reservas</a>
                  </li>
                  {% endif %}
                  {% if perms.core.view_agenda %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'calendariomedico' %}">Calendario medico</a>
                  </li>
                  {% endif %}
                  </li>
                  {% if user.is_authenticated %}
                  <li>  
                    <a href="{% url 'logout' %}">Cerrar sesión</a>
                  </li>
                  <li>
                    <a href="#">@{{ user.username }}</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Iniciar sesión</a>
                  </li> 
                  {% endif %}


              
                </ul>
              </div>
               
            </div>
          </nav>

        {% block contenido %}
            
        {% endblock contenido %}
        
    
  {% block scripts %}    
  {% endblock %}

     
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  {% if messages %}
  {% for m in messages %}
        <script>
          Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "succes"
          })
        </script>
  {% endfor %}
  {% endif %} 

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  
  
  
 
</body>

</html>

core/templates/core/calendariomedico.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}
<br>
<br>
<div class="container">
    <div class="row text-center">
      {% for a in agenda %}
          <div class="col-md-4 pb-1 pb-md-0">
            <div class="card">
              <div class="card-body">
                <p class="card-text">Nombre Medico: {{ a.medico }}</p>
                <p class="card-text">Fecha: {{ a.fecha_asignado }}</p>
                <p class="card-text">numero de reserva:{{ a.reserva}}</p>
                <button class="btn ">Aceptar
              </div>
            </div>        
          </div>
      {% endfor %}
    </div>
</div>
{% endblock %}


{% block scripts %}

{% endblock %}

core/templates/core/fullcalendar.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'fullcalendar/lib/main.css '%}">

{% load crispy_forms_tags %}
<br>
<br>
<div class="container">
<div class="row">
    <div class="col-12 col-md-6 offset-md-3 ">
        <div class="card">
            <div class="card-body ">
                <h2>Calendario Medico </h2>
                <h3>{{mensaje}}</h3>
                <hr>


                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <br>

                    <div id ="calendar"></div>
                 
                    

                </form>
                <div id ="calendar"></div>
                


            </div>
        </div>




    </div>

</div>
</div>

{% block extrajs %}

<script src ="{% static 'fullcalendar/lib/main.js' %}"></script>
<script>
    
    document.addEventListener('DOMContentLoaded', function(){
        var calendarUI = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarUI,{

        });
        calendar.render();

       
    });
       

</script>


{% endblock extrajs %}



{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    <header class="header" id="inicio">
       
        <div class="contenedor head">
            <h1 class="titulo">Clinica Dos Alamos</h1>
            <p class="copy">Porque tu salud es nuestra prioridad.</p>
        </div>
        
    </header>
    <main>
        <section class="services contenedor" id="servicio">
            <h2 class="subtitulo">Nuestro servicio</h2>
            <div class="contenedor-servicio">
                <img src="/media/medico1.png" alt="">
                <div class="checklist-servicio">
                    <div class="service">
                        <h3 class="n-service"><span class="number">1</span>Mejor atencion</h3>
                        <p> Medicos dispuestos a ofrecer la mejor calidad de atencion.</p>
                    </div>
                    <div class="service">
                        <h3 class="n-service"><span class="number">2</span>Medicos especializados</h3>
                        <p> Nos aseguramos de tener medicos para cada area que necesites.</p>
                    </div>
                    <div class="service">
                        <h3 class="n-service"><span class="number">3</span>Sexoooooo</h3>
                        <p> Sexoooooooooooooooooooooooooooooooooooooooo.</p>
                    </div>
                </div>
            </div>
        </section>
        <div class="imagen-light">
            <img src="/media/close.svg" alt="" class="close">
            <img src="" alt="" class="agregar-imagen">
        </div>
       
        <footer>
  
            <div class="contenedor footer-content">
              <div class="contact-us">
                  <h2 class="brand">Dos Alamos</h2>
                  <p>Clinica</p>
              </div>
              <div class="social-media">
                  <a href="./" class="social-media-icon">
                      <i class='bx bxl-facebook'></i>
                  </a>
                  <a href="./" class="social-media-icon">
                      <i class='bx bxl-twitter' ></i>
                  </a>
                  <a href="./" class="social-media-icon">
                      <i class='bx bxl-instagram' ></i>
                  </a>
              </div>
          </div>
        </footer>
        
{% endblock contenido %}

core/templates/core/listado_pago.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}

{% load crispy_forms_tags %}
{% load humanize %}
<div class="card">
    <div class="card-body">
        <h2>Listado de pago </h2>
        <hr>

        <table class="table table-striped table-dark table-responsive-sm">
            <tr>
                <th>Numero Reserva</th>
                <th>Fecha</th>
                <th>Total</th>
            </tr>
            {% for p in Pago %}
            <tr>
                <td>{{p.Reserva}}</td>
                <td>{{p.fecha_pago | date}}</td>
                <td>${{p.Total_pago | intcomma}}</td>   
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
    



{% endblock %}

core/templates/core/listado_reserva.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}

{% load crispy_forms_tags %}

<div class="card">
    <div class="card-body">
        <h2>Listado  de reservas</h2>
        <hr>

        <table class="table table-striped table-dark table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>RUN</th>
                <th>Prevision</th>
                <th>Fecha</th>
                <th>Sexo</th>
                <th>Correo</th>
                <th>Especialidad</th>
                <th>Medico</th>
                <th>Opciones</th>
            </tr>
            {% for p in reserva %}
                    <tr>
                        <td>{{p.nombre | title }}</td>
                        <td>{{p.apellido | title }}</td>
                        <td>{{p.rut | title }}</td>
                        <td>{{p.prevision | title }}</td>
                        <td>{{p.fecha }}</td>
                        <td>{{p.sexo |title }}</td>
                        <td>{{p.correo}}</td>
                        <td>{{p.especialidad | title}}</td>
                        <td>{{p.medico | title}}</td>
                        <td>
                            <a href="{% url 'modificar_reserva' p.id    %}" class="btn btn-dark">Modificar</a>
                            <a href="{% url 'eliminar_reserva' p.id    %}" class="btn btn-danger">Eliminar</a>
                            
                        </td>
                    </tr>
            {% endfor %}


    



    {% endblock %}

core/templates/core/modificar_reserva.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<br>

<div class="row">
    <div class="col-12 col-md-6 offset-md-3 ">
        <div class="card">
            <div class="card-body ">
                <h2>Editar reserva</h2>
                <hr>


                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnGuardar" class="btn btn-primary">Modificar</button>

                    </div>

                </form>
                {{mensaje}}


            </div>
        </div>




    </div>

</div>



{% endblock %}

core/templates/core/registropago.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}


{% load crispy_forms_tags %}
<br>
<br>

<div class="row" id="imprimir">
    <div class="col-12 col-md-6 offset-md-3 ">
        <div class="card">
            <div class="card-body">
                <h2 >Registro de pago Dos Alamos </h2>
                <hr>

                <h3>{{mensaje}}</h3> 
                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Registrar</button>

                    </div>

                </form>
                


            </div>
        </div>




    </div>

</div>



{% endblock %}

{% block scripts %} 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
<script>
  var doc = new jsPDF()

  var div = document.querySelector('#imprimir')
  doc.fromHTML(div,15,15)
  doc.save("comprobante_de_pago.pdf")



</script>

{% endblock %}

core/templates/core/reservahora.html
{% extends 'core/base.html' %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
{% endblock %}
{% block contenido %}

{% load crispy_forms_tags %}
<br>
<br>
<div class="container">
<div class="row">
    <div class="col-12 col-md-6 offset-md-3 ">
        <div class="card">
            <div class="card-body ">
                <h2>Reserva de hora </h2>
                <h3>{{mensaje}}</h3>
                <hr>


                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-dark">Reservar</button>
                                                                               
                    </div>

                </form>
                


            </div>
        </div>




    </div>

</div>
</div>



{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function() {
        $('#datetimepicker1').datetimepicker();
    });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}